apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mailsender
  name: mailsender
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app: mailsender
status:
  loadBalancer: {}
